'Collect, Zip?, and Attach DXF's to Drawing
Imports System.IO
Imports System.IO.Path
Imports System.Collections
Imports My.Computer.FileSystem

Sub Main()

	' Dim oDoc as Document = ThisApplication.ActiveDocument
	' If Not isDwg(oDoc) Then
		' MsgBox("Please run from a Drawing file.  ")
		' Exit Sub
	' End If
	

	Dim collectFolder As String = FilePath(oDoc.FullFileName) & BaseFilename(oDoc.FullFileName) & " DXF\"
	If System.IO.Directory.Exists(collectFolder) Then
		System.IO.Directory.Delete(collectFolder, True)
	End If
	
	Dim oAppend As System.IO.StreamWriter
	Dim oFile As String = "C:\_vaultWIP\Designs\dbug.log"
	
	Try
		oAppend = IO.File.AppendText(oFile)
	Catch
		noWrite = True
	End Try
	
	If noWrite = False Then
		oAppend.WriteLine(ThisApplication.UserName & "," & DateTime.Now.ToString("G") & "," & DocumentFileNameExt(oDoc))
	End If
	
	Dim oRefDocs as DocumentsEnumerator = oDoc.AllReferencedDocuments
	Dim copiedFileName As String
	
	Dim RefDwgFullFileName As String
	Dim RefDwgDocFileName As String 
	Dim RefDwgBaseFileName As String
	
	Dim RefDwgFullFileNamePN As String
	Dim RefDwgDocFileNamePN As String
	Dim RefDwgBaseFileNamePN As String
	
	Dim iProps as PropertySet
	Dim RefPN
	
	For Each oRefDoc in oRefDocs
		iProps = oRefDoc.PropertySets.Item("Design Tracking Properties")
		RefPN = iProps.Item("Part Number")
		
		
		oAppend.Write(oRefDoc.FullFileName & ",")
		
		RefDwgFullFileName = FindDrawingFile(oRefDoc)
		oAppend.Write(RefDwgFullFileName & ",")
		
		If RefDwgFullFileName.Length > 5 Then 
			RefDwgDocFileName = DocumentFileName(RefDwgFullFileName)
			RefDwgBaseFileName = BaseFilename(RefDwgFullFileName)
		End If
		
		RefDwgFullFileNamePN = FindDrawingFilePN(oRefDoc)
		oAppend.Write(RefDwgFullFileNamePN & ",")
		
		If RefDwgFullFileNamePN.Length > 5 Then	
			RefDwgDocFileNamePN = DocumentFileName(RefDwgFullFileNamePN)
			RefDwgBaseFileNamePN = BaseFilename(RefDwgFullFileNamePN)
		End If
		
		If RefDwgFullFileName <> "" Then
			'look for files with the same file name as ref doc, in the project location
			FileNameDXF = RefDwgDocFileName & ".dxf"
			oAppend.Write(FileNameDXF & ",")
			If System.IO.File.Exists(FileNameDXF) Then 'search for single page drawings
				copiedFileName = collectFolder & RefDwgBaseFileName & ".dxf"
				System.IO.Directory.CreateDirectory(collectFolder)
				My.Computer.FileSystem.CopyFile(FileNameDXF, copiedFileName, Microsoft.VisualBasic.FileIO.UIOption.AllDialogs, Microsoft.VisualBasic.FileIO.UICancelOption.DoNothing)
			End If
			
			'look for drawing file with the same file name as the ref doc, in the project location, page 1-10
			For i = 1 to 10 'search for pages 1-10
				FileNameDXF = RefDwgDocFileNamePN & " p" & i & ".dxf"
				oAppend.Write(FileNameDXF & ",")
				If System.IO.File.Exists(FileNameDXF) Then
					copiedFileName = collectFolder & RefDwgBaseFileName & " p" & i & ".dxf"
					System.IO.Directory.CreateDirectory(collectFolder)
					My.Computer.FileSystem.CopyFile(FileNameDXF, copiedFileName, Microsoft.VisualBasic.FileIO.UIOption.AllDialogs, Microsoft.VisualBasic.FileIO.UICancelOption.DoNothing)
				End If
			Next 
		End If
		
		If RefDwgFullFileNamePN <> "" Then
			'look for files with the part number of the ref doc, in the project location
			FileNameDXF =  Left(RefDwgDocFileNamePN, RefDwgDocFileNamePN.Length - RefPN.Value.Length) & ".dxf"
			oAppend.Write(FileNameDXF & ",")
			If System.IO.File.Exists(FileNameDXF) Then 'search for single page drawings
				copiedFileName = collectFolder & RefDwgBaseFileNamePN &  ".dxf"
				System.IO.Directory.CreateDirectory(collectFolder)
				My.Computer.FileSystem.CopyFile(FileNameDXF, copiedFileName, Microsoft.VisualBasic.FileIO.UIOption.AllDialogs, Microsoft.VisualBasic.FileIO.UICancelOption.DoNothing)
			End If
					
			'look for files with the part number of the ref doc, in the project location, page 1-10
			For i = 1 to 10 'search for pages 1-10 by part number
				FileNameDXF = Left(RefDwgDocFileNamePN, RefDwgDocFileNamePN.Length - RefPN.Value.Length) & " p" & i & ".dxf"
				oAppend.Write(FileNameDXF)
				If System.IO.File.Exists(FileNameDXF) Then
					copiedFileName = collectFolder & RefDwgBaseFileNamePN & " p" & i & ".dxf"
					System.IO.Directory.CreateDirectory(collectFolder)
					My.Computer.FileSystem.CopyFile(FileNameDXF, copiedFileName, Microsoft.VisualBasic.FileIO.UIOption.AllDialogs, Microsoft.VisualBasic.FileIO.UICancelOption.DoNothing)
				End If
			Next
		End If
		oAppend.WriteLine("")
	Next
	
	If System.IO.Directory.Exists(collectFolder) Then
		Process.Start(collectFolder)
	End If
	
	oAppend.Flush()
	oAppend.Close()
	
	MsgBox("Done")
	
End Sub

Function FindDrawingFile(PartOrAssemblyDoc As Document)
    Dim fullFilename As String
    fullFilename = PartOrAssemblyDoc.fullFilename
   
    ' Extract the path from the full filename.
    Dim path As String
    path = "C:\_vaultWIP\Designs"
   
    ' Extract the filename from the full filename.
    Dim filename As String
    filename = Right$(fullFilename, Len(fullFilename) - InStrRev(fullFilename, "\"))
   
    ' Replace the extension with "dwg"
    filename = Left$(filename, InStrRev(filename, ".")) & "dwg"
   
    ' Find if the drawing exists.
    Dim drawingFilename As String
    drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
    ' Check the result.
    If drawingFilename = "" Then
        ' Try again with idw extension.
        filename = Left$(filename, InStrRev(filename, ".")) & "idw"
       
        ' Find if the drawing exists.
        drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
        ' Return the result.
        If drawingFilename <> "" Then
            FindDrawingFile = drawingFilename
        Else
            FindDrawingFile = ""
        End If
    Else
        ' Return the result.
        FindDrawingFile = drawingFilename
    End If
End Function

Function FindDrawingFilePN(PartOrAssemblyDoc As Document)
    Dim fullFilenamePN As String
    fullFilenamePN = PartOrAssemblyDoc.fullFilename
   
    ' Extract the path from the full filename.
    Dim path As String = "C:\_vaultWIP\Designs"
    'path = Left$(fullFilenamePN, InStrRev(fullFilenamePN, "\"))
   
	Dim iProps as PropertySet = PartOrAssemblyDoc.PropertySets.Item("Design Tracking Properties")
	Dim pn = iProps.Item("Part Number")
	
    Dim filename As String = pn.Value
    'filename = Right$(fullFilenamePN, Len(fullFilenamePN) - InStrRev(fullFilenamePN, "\"))
   
    ' Replace the extension with "dwg"
    filename = filename & ".dwg"
   
    ' Find if the drawing exists.
    Dim drawingFilename As String
    drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
    ' Check the result.
    If drawingFilename = "" Then
        ' Try again with idw extension.
        filename = filename & "idw"
       
        ' Find if the drawing exists.
        drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
        ' Return the result.
        If drawingFilename <> "" Then
            Return drawingFilename
        Else
            Return ""
        End If
    Else
        ' Return the result.
         Return drawingFilename
    End If
End Function

Function isDwg(ThisDoc as Document) As Boolean
	Debug.Print (ThisDoc.DocumentType)
	If ThisDoc.DocumentType = kDrawingDocumentObject
		isDwg = True
	Else 
		isDwg = False
	End If
End Function

Function DocumentFileName(Doc As String) As String
	DocumentFileName = Left(Doc, Doc.Length - 4)
	'MsgBox(DocumentFileName)
End Function

' Function DocumentFileNameOLD(Doc As Document) As String
	' Dim FilePath as String
	' FilePath = Doc.FullFileName
	' DocumentFileName = IO.Path.GetFileNameWithoutExtension(FilePath)
	' 'MsgBox(DocumentFileName)
' End Function

Function BaseFilename(ByVal fullFilename As String) As String
    Dim temp As String
    temp = Right(fullFilename, Len(fullFilename) - InStrRev(fullFilename, "\"))
    BaseFilename = Left(temp, InStrRev(temp, ".") - 1)
End Function

Function FilePath(ByVal fullFilename As String) As String
    FilePath = Left(fullFilename, InStrRev(fullFilename, "\"))
End Function

Function DocumentFileNameExt(Doc as Document) As String
	DocumentFileNameExt = IO.Path.GetFileName(Doc.FullFileName)
End Function