'https://forums.autodesk.com/t5/inventor-customization/possible-to-check-all-members-of-factory-for-errors-using-ilogic/m-p/3863094/highlight/true#M43278
sub Main()
	Dim app As Inventor.Application = ThisApplication
	Dim oDoc As Inventor.Document = app.ActiveDocument
	Dim oCompDef As ComponentDefinition = oDoc.ComponentDefinition
	Dim currow As Integer
	Dim opFactory As iPartFactory
	Dim opRow As iPartTableRow
	Dim Max As Integer = 10

	InventorVb.DocumentUpdate()

	opFactory = ThisApplication.ActiveDocument.ComponentDefinition.iPartFactory
	currow = opFactory.DefaultRow.Index
	opFactory.DefaultRow = opFactory.TableRows.Item(1)
	Dim props = ThisApplication.ActiveDocument.PropertySets.Item("Design Tracking Properties")
	Dim pPN = props.Item("Part Number")

	
	
	filename = ThisApplication.ActiveDocument.FullFileName
	
	Dim searchPath = Left$(filename, InStrRev(filename, "\")) & IO.Path.GetFileNameWithoutExtension(filename) & "\"
	msgbox(searchPath)
	
	
	
	If opFactory.TableRows.Count > Max
		Proceed = MessageBox.Show("This will create " & opFactory.TableRows.Count & " files, and may take some time to execute.  Do you want to continue?  ", "Time Warning",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)
	Else
		Proceed = vbYes
	End If

	If Proceed = vbYes
		' Iterate through the rows
		For Each opRow In opFactory.TableRows
			opFactory.DefaultRow=opRow			
			opRowFile = FindDrawingFileByName(searchPath & pPN.Value & ".ipt")
			
			If opRowFile <> "" Then
				'ThisApplication.Documents.Open(opRowFile)
				msgbox("Yes - " & opRowFile)
			End If
		Next
		opFactory.DefaultRow=opFactory.TableRows.Item(currow)
	End If
	
	MsgBox("Done")
	
End Sub



' Find the drawing for the specified part of assembly.
Function FindDrawingFileByName(PartOrAssemblyDoc As String)
    Dim fullFilename As String
    fullFilename = PartOrAssemblyDoc
	
    ' Extract the path from the full filename.
    Dim path As String
    path = "C:\_vaultWIP\Designs\" 'Left$(fullFilename, InStrRev(fullFilename, "\"))
   
    ' Extract the filename from the full filename.
    Dim filename As String
    filename = Right$(fullFilename, Len(fullFilename) - InStrRev(fullFilename, "\"))
   
    ' Replace the extension with "dwg"
    filename = Left$(filename, InStrRev(filename, ".")) & "dwg"
   
    ' Find if the drawing exists.
    Dim drawingFilename As String
    drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
    ' Check the result.
    If drawingFilename = "" Then
        ' Try again with idw extension.
        filename = Left$(filename, InStrRev(filename, ".")) & "idw"
       
        ' Find if the drawing exists.
        drawingFilename = ThisApplication.DesignProjectManager.ResolveFile(path, filename)
   
        ' Return the result.
        If drawingFilename <> "" Then
            FindDrawingFile = drawingFilename
        Else
            FindDrawingFile = ""
        End If
    Else
        ' Return the result.
        FindDrawingFile = drawingFilename
    End If
End Function

