Imports System.IO
Imports System.IO.Path
Imports System.Collections


Sub Main()
'declarations
	Dim oDoc as Document
	Dim compOcc as ComponentOccurrence
	customPropertySet = ThisDoc.Document.PropertySets.Item("Inventor User Defined Properties")
	'Dim DirMgr = System.IO.Directory
	
'Main
	oDoc = ThisApplication.ActiveEditDocument

	' SharedVariable("LogVar") = "Export STL"
	' iLogicVB.RunExternalRule("Write SV to Log.iLogicVB")
	
	If oDoc.FileSaveCounter >= 1 Then
		' Are we in a Assembly or Part Document?
		If oDoc.DocumentType = kAssemblyDocumentObject Or oDoc.DocumentType = kPartDocumentObject Then
			
			Dim CurDate as Date = DateTime.Now 'pull current date stamp		
			
			strlongDate = CurDate.ToString("D")
			
			Dim folderDate as Date
			
			If strlongDate.Contains("Saturday") = True Then
				folderDate = DateAndTime.DateAdd(DateInterval.Day, 2, CurDate)
			Else If strlongDate.Contains("Sunday") = True Then
				folderDate = DateAndTime.DateAdd(DateInterval.Day, 1, CurDate)
			Else 
				folderDate = CurDate
			End If
			
			DateFolder = folderDate.ToString("yyyyMMdd")
			oPath = "\\RD-Zeus\MultiJet Print Queue\" & DateFolder 'ThisDoc.Path
			System.IO.Directory.CreateDirectory(oPath)
			
			oFileName = IO.Path.GetFileNameWithoutExtension(oDoc.FullFileName)
			
			oSTLAddIn = ThisApplication.ApplicationAddIns.ItemById("{81CA7D27-2DBE-4058-8188-9136F85FC859}")
			oContext = ThisApplication.TransientObjects.CreateTranslationContext
			oContext.Type = IOMechanismEnum.kFileBrowseIOMechanism
			oOptions = ThisApplication.TransientObjects.CreateNameValueMap
			oDataMedium = ThisApplication.TransientObjects.CreateDataMedium

			If oSTLAddIn.HasSaveCopyAsOptions(oDataMedium, oContext, oOptions) Then
				oOptions.Value("ExportUnits") = 5 
					'INCH = 2
					'FOOT = 3
					'CENTIMETER = 4
					'MILLIMETER = 5
					'METER = 6
					'MICRON = 7
				oOptions.Value("Resolution") = 0
					'HIGH = 0
					'MEDIUM = 1
					'LOW = 2
					'CUSTOM = 3 
					'BREP = 4
				oOptions.Value("ExportFileStructure") = 0
					'ONE FILE = 0
					'ONE FILE PER PART INSTANCE = 1 
			End If
			
			oDataMedium.FileName = oPath & "\" & oFileName & ".stl"

			'Publish document
			oSTLAddIn.SaveCopyAs(oDoc, oContext, oOptions, oDataMedium)
			
		Else
		
			MessageBox.Show("This command can only be used in an Assembly or Part.")
			
		End If
	Else
	
		MessageBox.Show("File must be saved to continue.", "File Not Saved",MessageBoxButtons.OK,MessageBoxIcon.Error)

	End If
End Sub