'declarations
	Dim oAsmDoc as Document
	Dim compOcc as ComponentOccurrence
	customPropertySet = ThisDoc.Document.PropertySets.Item("Inventor User Defined Properties")
	
'Main
	oAsmDoc = ThisApplication.ActiveEditDocument

	SharedVariable("LogVar") = "Export STL"
	iLogicVB.RunExternalRule("Write SV to Log.iLogicVB")
	
	If oAsmDoc.FileSaveCounter >= 1 Then
		' Are we in a Assembly or Part Document?
		If oAsmDoc.DocumentType = kAssemblyDocumentObject Or oAsmDoc.DocumentType = kPartDocumentObject Then
		
			'Check for property "STL" and create it if not found.  
			Try
				  prop = customPropertySet.Item("STL")
			Catch
				  ' Assume error means not found
				  customPropertySet.Add("", "STL")
				  iProperties.Value("Custom", "STL") = False
			End Try

			'Check iproperty to see if rule has been run, warn user if it has.  
			If iProperties.Value("Custom", "STL") = True Then
				MessageBox.Show("File has already been created.  The file must be checked out to continue.  Are you sure you want to continue?", "Existing File!",MessageBoxButtons.OKCancel)
			End If
			
			oPath = ThisDoc.Path
			oFileName = ThisDoc.FileName(False) 'without extension
			oRevNum = iProperties.Value("Project", "Revision Number")
			oSTLAddIn = ThisApplication.ApplicationAddIns.ItemById _
			("{81CA7D27-2DBE-4058-8188-9136F85FC859}")
			oDocument = ThisApplication.ActiveDocument
			oContext = ThisApplication.TransientObjects.CreateTranslationContext
			oContext.Type = IOMechanismEnum.kFileBrowseIOMechanism
			oOptions = ThisApplication.TransientObjects.CreateNameValueMap
			oDataMedium = ThisApplication.TransientObjects.CreateDataMedium

			If oSTLAddIn.HasSaveCopyAsOptions(oDataMedium, oContext, oOptions) Then
				oOptions.Value("ExportUnits") = 5 
					'INCH = 2
					'FOOT = 3
					'CENTIMETER = 4
					'MILLIMETER = 5
					'METER = 6
					'MICRON = 7
				oOptions.Value("Resolution") = 0
					'HIGH = 0
					'MEDIUM = 1
					'LOW = 2
					'CUSTOM = 3 
					'BREP = 4
				oOptions.Value("ExportFileStructure") = 0
					'ONE FILE = 0
					'ONE FILE PER PART INSTANCE = 1 
			End If
			
			oDataMedium.FileName = oPath & "\" & oFileName & ".stl"

			'Publish document
			oSTLAddIn.SaveCopyAs(oDocument, oContext, oOptions, oDataMedium)
			
			
			
			'Pull path and File Name, append desired file type, and execute save as.  
			'FileName = ThisDoc.PathAndFileName(False)
			'FileNameSTL = FileName & ".stl"
			'ThisDoc.Document.SaveAs(FileNameSTL, True)
			
			
			If iProperties.Value("Custom", "STL") = False Then
			
				AttachFile = MessageBox.Show("Would you like to create this file as an attachment?", "Create Attachment?",MessageBoxButtons.YesNo,MessageBoxIcon.Question)
		
				If AttachFile = vbYes Then
			
					Dim oDoc As PartDocument
					oDoc = ThisApplication.ActiveDocument
					
					Dim kOLEDocumentLinkObject As ObjectTypeEnum
						kOLEDocumentLinkObject = 3331 'OLE link document
					
					Dim oRefOLE As ReferencedOLEFileDescriptors
					oRefOLE = oDoc.ReferencedOLEFileDescriptors 
					oRefOLE.Add(oPath & "\" & oFileName & ".stl", kOLEDocumentLinkObject)
					iProperties.Value("Custom", "STL") = True

				End If
			
			End If
			
		Else
		
			MessageBox.Show("This command can only be used in an Assembly or Part.")
			
		End If
	Else
	
		MessageBox.Show("File must be saved to continue.", "File Not Saved",MessageBoxButtons.OK,MessageBoxIcon.Error)

	End If
