Imports Inventor.ViewOrientationTypeEnum
Imports Inventor.DrawingViewStyleEnum
Imports Inventor.PointIntentEnum
Imports Inventor.DimensionTypeEnum
Imports Inventor.DrawingCurveSegmentEnum
Imports Inventor.DrawingCurveEnum
Imports Inventor.CurveTypeEnum


Sub Main()

	'Ask to Create Drawing
	AskCreateDrawing = vbYes 'MessageBox.Show("Would you like to Create Drawings for the Current Model?", "Drawing Automation",MessageBoxButtons.YesNo)
	
	'If the User Presses YES
	If AskCreateDrawing = vbYes Then 'AndAlso iProperties.Value("Custom", "HasDwg") = False Then
		
		iProperties.Value("Custom", "HasDwg") = True
		iProperties.Value("Custom", "DETAILER") = ThisApplication.UserName
		iProperties.Value("Project", "Creation Date") = DateString
		
		Dim uScale As Boolean = True
		
		uScale = InputRadioBox("Auto Scale?", "Yes", "No", uScale, Title := "Scale")
			
		'Set the View Scales
		Dim DrawingViewScale As Double 
		
		If uScale = True Then
			DrawingViewScale = 4/iProperties.Value("Custom", "LENGTH")
		Else 
			DrawingViewScale = InputBox("Enter Scale", "Scale", "1/1")
		End If
		
		Dim ModelDocName As String 
		ModelDocName = ThisDoc.FileName(False) 'without extension
		
		ModelDwgDoc = CreateDrawing_PlaceViews(ModelDocName, DrawingViewScale, "Top_Right_Project", oBaseView, oRightSideView, oProjectView, oView4)
		Dim oBW as Double
		Dim oBH As Double
		oBW = oBaseView.Width
		oBH = oBaseView.Height
		'MsgBox(oBW & " x " & oBH)
		
		
		
		'CreateOverallDimension (ModelDwgDoc, oBaseView, YDIM, "Vertical", 0.75, "Left", False)

		' ChuteTop = FindCurve (Assem_DrawingDoc, oBaseView, oBW, "Horizontal", "Top")
		' MsgBox("1")
		' FlangeEdge = FindCurve (Assem_DrawingDoc, oBaseView, oBH, "Vertical", "Right")
		' CreateOverallDimension(ModelDrawingDoc, "Vertical", "Right", ChuteTop, "Top", FlangeEdge, "Right", 0.5)
		
		'CreateLinearDimension (ModelDwgDoc, oBaseView, YDIM, "Vertical", 0.75, "Left", False)

		'CreateLinearDimension (ModelDwgDoc, oBaseView, iProperties.Value("Custom", "WIDTH"), "Horizontal", -0.75, "Bottom", True)
		
		'CreateLinearDimension (ModelDwgDoc, oRightSideView, iProperties.Value("Custom", "THICKNESS"), "Horizontal", 0.75, "Left", True)
		
		
		'Save As oDrawingDoc (Path and File Name)
		oPartPath = ThisDoc.Path
		oPartPathLength = Len(oPartPath)
		oDrawingPath = Left(oPartPath, oPartPathLength)
		
		oDrawingDoc = oDrawingPath & "\" & ModelDocName & ".dwg" 
			
		ModelDwgDoc.SaveAs(oDrawingDoc, False)
		'Close the Template Drawing
		ModelDwgDoc.Close(True)
		'Open the Newly Saved Drawing
		DrawingDoc = ThisApplication.Documents.Open(oDrawingDoc, True)
		
	End If

End Sub

Function CreateDrawing_PlaceViews (PartNumber As String, DrawingViewScale As Double, ViewsToPlace As String, ByRef oBaseView As DrawingView, ByRef oView2 As DrawingView, ByRef oView3 As DrawingView, ByRef oView4 As DrawingView)

	Dim oDrawDoc As DrawingDocument
	Dim oPartDoc As Document
	Dim oSheet As Sheet
	Dim oTG As TransientGeometry
	Dim oPoint1 As Point2d
	Dim oPoint2 As Point2d
	Dim oPoint3 As Point2d
	
	oPartDoc = ThisDoc.Document
	oDrawDoc = ThisApplication.Documents.Add(kDrawingDocumentObject, "C:\_vaultWIP\Designs\Templates\TT_Part.dwg", True)

	
	oSheet = oDrawDoc.Sheets.Item(1)
	oTG = ThisApplication.TransientGeometry
	
	'Set points in order to get wanted View (ie. if 'Y' is the same and 'X' is greater or less, you will get a Side View)
	oPoint1 = oTG.CreatePoint2d(10, 10)
	oPoint2 = oTG.CreatePoint2d(10, 20)
	oPoint3 = oTG.CreatePoint2d(30, 10)
	oPoint4 = oTG.CreatePoint2d(30, 20)
	

	Dim ViewStyles(0 To 3) As String
	ViewStyles(0) = "Hidden Lines"
	ViewStyles(1) = "Removed Hidden Lines"
	ViewStyles(2) = "Shaded w/ Hidden Lines"
	ViewStyles(3) = "Shaded w/ Removed Hidden Lines"
	
	Dim uViewStyle As String
	
	uViewStyle = InputListBox("Select View Style", ViewStyles, ViewStyles(1), "Drawing View Style", "Select One")
	
	Dim ViewStyle As DrawingViewStyleEnum
	
	If uViewStyle = "Hidden Lines" Then
			ViewStyle = 32257
	Else If uViewStyle = "Removed Hidden Lines"
			ViewStyle = 32258
	Else If uViewStyle = "Shaded w/ Hidden Lines"
			ViewStyle = 32259
	Else If uViewStyle = "Shaded w/ Hidden Lines Removed"
			ViewStyle = 32261
	End If
	
	'kFromBaseDrawingViewStyle = 32260
	'kHiddenLineDrawingViewStyle = 32257
	'kHiddenLineRemovedDrawingViewStyle = 32258
	'kShadedDrawingViewStyle = 32259
	'kShadedHiddenLineDrawingViewStyle = 32261
	
	'Create the Base View
	oBaseView = oSheet.DrawingViews.AddBaseView(oPartDoc, oPoint1, DrawingViewScale, kFrontViewOrientation, ViewStyle, "Default")
	
	
	'//////// Place the rest of the Projected Views According to the Parameter String Specified ////////////
	
	If ViewsToPlace = "Top" Then
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint2, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Right" 
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint3, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Project"
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint4, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Top_Right"
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint2, kFromBaseDrawingViewStyle, DrawingViewScale)
		oView3 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint3, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Top_Project"
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint2, kFromBaseDrawingViewStyle, DrawingViewScale)
		oView3 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint4, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Right_Project"
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint3, kFromBaseDrawingViewStyle, DrawingViewScale)
		oView3 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint4, kFromBaseDrawingViewStyle, DrawingViewScale)
		
	Else If ViewsToPlace = "Top_Right_Project"
		oView2 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint2, kFromBaseDrawingViewStyle, DrawingViewScale)
		oView3 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint3, kFromBaseDrawingViewStyle, DrawingViewScale)
		oView4 = oSheet.DrawingViews.AddProjectedView(oBaseView, oPoint4, kFromBaseDrawingViewStyle, DrawingViewScale)
	
	Else If ViewsToPlace = "None" Then
	'Only Place Base View, therefore do nothing
	End If
	
	
	'Return the Drawing Document 
	Return oDrawDoc

End Function


Function FindCurve (oDrawingDoc As DrawingDocument, oDrawingView As DrawingView, DimensionLength As Double, DirectionOfDim As String, DimensionLocation As String)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oDrawingCurve As DrawingCurve
	Dim oTG As TransientGeometry
	Dim Count As Integer
	Dim DrawingViewScale As Double
	
	DrawingViewScale = oDrawingView.Scale
	oTG = ThisApplication.TransientGeometry
	
	
			'//////////												//////////////////
	'//////////  SEE 'CreateLinearDimension' FOR THIS PORTION OF CODE  //////////////////
		'//////////												//////////////////
		
	If DimensionLocation = "Top" Or DimensionLocation = "Right" Then
		DrawingCurvePoint = oTG.CreatePoint2d(0, 0)
	Else If DimensionLocation = "Bottom" Or DimensionLocation = "Left" 
		DrawingCurvePoint = oTG.CreatePoint2d(100, 100)
	End If
	
	DrawingCurvePointX = DrawingCurvePoint.x
	
	Dim CurveCount As Integer
	CurveCount = 0
	
	For Each oDrawingCurve In oDrawingView.DrawingCurves
		CurveCount = CurveCount + 1
	Next
	
	
	For StartCount = 1 To CurveCount
		
		oDrawingCurve = oDrawingView.DrawingCurves.Item(StartCount)
		
		If oDrawingCurve.CurveType = kLineSegmentCurve Then
			
			Dim DimLength As DoubleForEquals
			
			If DirectionOfDim = "Vertical" Then
				DimLength = Abs(oDrawingCurve.StartPoint.y - oDrawingCurve.EndPoint.y)/DrawingViewScale/2.54
			Else If DirectionOfDim = "Horizontal" Then
				DimLength = Abs(oDrawingCurve.StartPoint.x - oDrawingCurve.EndPoint.x)/DrawingViewScale/2.54
			End If
MsgBox("FC-A")
MsgBox(DimensionLength)	
			If Abs(DimLength - DimensionLength) < 0.01 Then 
				If DirectionOfDim = "Vertical" And DimensionLocation = "Right" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Vertical" And DimensionLocation = "Left" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Top" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Bottom" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
				End If
			End If
		End If
	Next
	
	Return CorrectCurve

End Function

Function CreateLinearDimension (oDrawingDoc As DrawingDocument, oDrawingView As DrawingView, DimensionLength As DoubleForEquals, DirectionOfDim As String, OffsetDistance As Double, DimensionLocation As String, ReferencedDim As Boolean)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)

	Dim oDrawingCurve As DrawingCurve
	Dim oTG As TransientGeometry
	Dim Count As Integer
	Dim DrawingViewScale As Double

	DrawingViewScale = oDrawingView.Scale
	oTG = ThisApplication.TransientGeometry
	
	'Set up Phantom points in order to locate the Wanted lines 
	'(If you want To find the lower line, you must start With a higher point And work your way down)
	If DimensionLocation = "Top" Or DimensionLocation = "Right" Then
		DrawingCurvePoint = oTG.CreatePoint2d(0, 0)
	Else If DimensionLocation = "Bottom" Or DimensionLocation = "Left" 
		DrawingCurvePoint = oTG.CreatePoint2d(100, 100)
	End If
	
	'The 'X' is used for both the 'X' and 'Y' when locating the point
	'It Is only a place holder so that the variables match for programming
	DrawingCurvePointX = DrawingCurvePoint.x
	
	Dim CurveCount As Integer
	CurveCount = 0
	
	'Find the amount of curves in the specified view
	For Each oDrawingCurve In oDrawingView.DrawingCurves
		CurveCount = CurveCount + 1
	Next
	
	'From the First Curve until the Last Curve (All curves based on the last For loop)
	For StartCount = 1 To CurveCount
		
		'Select the curve
		oDrawingCurve = oDrawingView.DrawingCurves.Item(StartCount)
		
		'If this curve is Linear
		If oDrawingCurve.CurveType = kLineSegmentCurve Then
			
			Dim DimLength As DoubleForEquals
			
			'Get the Length of the Curve based on the Orientation passed into the Sub
			'Abs(a - b) gives you the number whether it is a negative number or positive, it will always convert to positive
			'This Number is in Sheet Space and 'cm', Divide by the View Scale and by 2.54 to convert to Model Space and 'in'
			If DirectionOfDim = "Vertical" Then
				DimLength = Abs(oDrawingCurve.StartPoint.y - oDrawingCurve.EndPoint.y)/DrawingViewScale/2.54
			Else If DirectionOfDim = "Horizontal" Then
				DimLength = Abs(oDrawingCurve.StartPoint.x - oDrawingCurve.EndPoint.x)/DrawingViewScale/2.54
			End If
			
			'If this Curve is Equal to the Wanted Dimension Specified by the Parameter Passed into the Sub (Within Tolerance)
			If Abs(DimLength - DimensionLength) < 0.0001 Then 
			
				'Based on the direction you want the line to be towards, this computes appropriate calculations for each direction
				'If the calculation Proves to be right (This Curve is farther towards the specified side than the previous curve)
				'Then the current curve will be saved as the Correct one
				If DirectionOfDim = "Vertical" And DimensionLocation = "Right" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Vertical" And DimensionLocation = "Left" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Top" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Bottom" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
				End If
			End If
		End If
	Next
	
	
	Dim oDim As LinearGeneralDimension
	Dim oPt As Point2d
	Dim oPlaceDimX As Double
	Dim oPlaceDimY As Double
	Dim oIntent1 As GeometryIntent
	Dim oIntent2 As GeometryIntent
	
	'Create the Intent points based on the Correct Curve found through the For Loop
	oIntent1 = oSheet.CreateGeometryIntent(CorrectCurve, kStartPointIntent)
	oIntent2 = oSheet.CreateGeometryIntent(CorrectCurve, kEndPointIntent)
	
	'Offset the Text in the appropriate direction based on the Curve orientation and center
	If DirectionOfDim = "Vertical" Then
		oPlaceDimX = CorrectCurve.MidPoint.x + OffsetDistance
		oPlaceDimY = CorrectCurve.MidPoint.y
	
	Else If DirectionOfDim = "Horizontal"
		oPlaceDimX = CorrectCurve.MidPoint.x
		oPlaceDimY = CorrectCurve.MidPoint.y + OffsetDistance
	End If
	
	'Create the Point using these locations
	oPt = oTG.CreatePoint2d(oPlaceDimX, oPlaceDimY)
	
	
	'Set the Appropriate Style based on the Parameter passed into the Sub
	'(These Styles are pre set up in the Drawing Template)
	Dim DimStyle As DimensionStyle
	
	If ReferencedDim = False Then
		DimStyle = oDrawingDoc.StylesManager.DimensionStyles.Item("TT_2_Dec")
	
	Else If ReferencedDim = True 
		DimStyle = oDrawingDoc.StylesManager.DimensionStyles.Item("REF TT_2_Dec")
	End If
	
	
	'Set the Type of dimension to create
	Dim TypeOfDim As String
	
	If DirectionOfDim = "Vertical" Then
		TypeOfDim = kVerticalDimensionType
	Else If DirectionOfDim = "Horizontal" 
		TypeOfDim = kHorizontalDimensionType
	End If
	
	
	'Create the Dimension and Re-Center the text inbetween the leaders
	Dim oDimension As DrawingDimension
	oDimension = oSheet.DrawingDimensions.GeneralDimensions.AddLinear(oPt, oIntent1, oIntent2, TypeOfDim, True, DimStyle)
	oDimension.CenterText
	
	'Return this Dimension
	Return oDimension

End Function

Function CreateAlignedDimension (oDrawingDoc As DrawingDocument, oDrawingView As DrawingView, DimensionLength As DoubleForEquals, DirectionOfDim As String, OffsetDistance As Double, DimensionLocation As String, DimensionType As String, ReferencedDim As Boolean)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oDrawingCurve As DrawingCurve
	Dim CorrectCurve As DrawingCurve
	Dim oTG As TransientGeometry
	Dim StartCount As Integer
	Dim DrawingViewScale As Double
	
	DrawingViewScale = oDrawingView.Scale
	oTG = ThisApplication.TransientGeometry
	
	'Set up Phantom points in order to locate the Wanted lines 
	'(If you want To find the lower line, you must start With a higher point And work your way down)
	If DimensionLocation = "Top" Or DimensionLocation = "Right" Then
		DrawingCurvePoint = oTG.CreatePoint2d(0, 0)
	Else If DimensionLocation = "Bottom" Or DimensionLocation = "Left" 
		DrawingCurvePoint = oTG.CreatePoint2d(100, 100)
	End If
	
	'The 'X' is used for both the 'X' and 'Y' when locating the point
	'It Is only a place holder so that the variables match for programming
	DrawingCurvePointX = DrawingCurvePoint.x
	
	Dim CurveCount As Integer
	CurveCount = 0
	
	'Find the amount of curves in the specified view
	For Each oDrawingCurve In oDrawingView.DrawingCurves
		CurveCount = CurveCount + 1
	Next
	
	'From the First Curve until the Last Curve (All curves based on the last For loop)
	For StartCount = 1 To CurveCount
		
		'Select the Curve
		oDrawingCurve = oDrawingView.DrawingCurves.Item(StartCount)
		
		'If this Curve is linear
		If oDrawingCurve.CurveType = kLineSegmentCurve Then
		
			Dim DimLength As DoubleForEquals
			
			'Get the Length of the Curve based on the Orientation passed into the Sub
			'Abs(a - b) gives you the number whether it is a negative number or positive, it will always convert to positive
			'This Number is in Sheet Space and 'cm', Divide by the View Scale and by 2.54 to convert to Model Space and 'in'
			If DirectionOfDim = "Vertical" Then
				DimLength = Abs(oDrawingCurve.StartPoint.y - oDrawingCurve.EndPoint.y)/DrawingViewScale/2.54
			Else If DirectionOfDim = "Horizontal" Then
				DimLength = Abs(oDrawingCurve.StartPoint.x - oDrawingCurve.EndPoint.x)/DrawingViewScale/2.54
			End If
			
			'If this Curve is Equal to the Wanted Dimension Specified by the Parameter Passed into the Sub (Within Tolerance)
			If Abs(DimLength - DimensionLength) < 0.0001 Then 
			
				'Based on the direction you want the line to be towards, this computes appropriate calculations for each direction
				'If the calculation Proves to be right (This Curve is farther towards the specified side than the previous curve)
				'Then the current curve will be saved as the Correct one
				If DirectionOfDim = "Vertical" And DimensionLocation = "Right" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX < oDrawingCurve.EndPoint.x
						DrawingCurvePointX = oDrawingCurve.EndPoint.x
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Vertical" And DimensionLocation = "Left" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX > oDrawingCurve.EndPoint.x
						DrawingCurvePointX = oDrawingCurve.EndPoint.x
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Top" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX < oDrawingCurve.EndPoint.y
						DrawingCurvePointX = oDrawingCurve.EndPoint.y
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Bottom" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX > oDrawingCurve.EndPoint.y
						DrawingCurvePointX = oDrawingCurve.EndPoint.y
						CorrectCurve = oDrawingCurve
					End If
				End If
			End If
		End If
	Next
	
	
	Dim oDim As LinearGeneralDimension
	Dim oPt As Point2d
	Dim oPlaceDimX As Double
	Dim oPlaceDimY As Double
	Dim oIntent1 As GeometryIntent
	Dim oIntent2 As GeometryIntent
	
	
	'Create the Intent points based on the Correct Curve found through the For Loop
	oIntent1 = oSheet.CreateGeometryIntent(CorrectCurve, kStartPointIntent)
	oIntent2 = oSheet.CreateGeometryIntent(CorrectCurve, kEndPointIntent)
	
	
	
	'Brings the Dimension Text to the furthest Point based on the whether Offset distance is '-' or '+'
	'This is to keep the same effect in using OffsetDistance as a Linear Dimension
	Dim LineOffset As Double
	
	If OffsetDistance < 0 Then
		If DirectionOfDim = "Vertical" Then
			LineOffset = -Abs(CorrectCurve.StartPoint.x - CorrectCurve.EndPoint.x)/2 'Horizontal
		Else If DirectionOfDim = "Horizontal"
			LineOffset = -Abs(CorrectCurve.StartPoint.y - CorrectCurve.EndPoint.y)/2 'Vertical
		End If
	Else If OffsetDistance >= 0 
		If DirectionOfDim = "Vertical" Then
			LineOffset = Abs(CorrectCurve.StartPoint.x - CorrectCurve.EndPoint.x)/2 'Horizontal
		Else If DirectionOfDim = "Horizontal"
			LineOffset = Abs(CorrectCurve.StartPoint.y - CorrectCurve.EndPoint.y)/2 'Vertical
		End If
	End If
	
	
	'Offset the Text in the appropriate direction based on the Curve orientation and center
	If DirectionOfDim = "Vertical" Then
		oPlaceDimX = CorrectCurve.MidPoint.x + LineOffset + OffsetDistance
		oPlaceDimY = CorrectCurve.MidPoint.y
	
	Else If DirectionOfDim = "Horizontal"
		oPlaceDimX = CorrectCurve.MidPoint.x
		oPlaceDimY = CorrectCurve.MidPoint.y + LineOffset + OffsetDistance
	End If
	
	'Create the Point using the above Values
	oPt = oTG.CreatePoint2d(oPlaceDimX, oPlaceDimY)
	
	
	'Set the Appropriate Style based on the Parameter passed into the Sub
	'(These Styles are pre set up in the Drawing Template)
	Dim DimStyle As DimensionStyle
	
	If ReferencedDim = False Then
		DimStyle = oDrawingDoc.StylesManager.DimensionStyles.Item("GT - Fraction (ANSI)")
	
	Else If ReferencedDim = True 
		DimStyle = oDrawingDoc.StylesManager.DimensionStyles.Item("GT - Reference Fraction (ANSI)")
	End If
	
	
	'Set the type of dimension to create
	Dim TypeOfDim As String
	
	If DimensionType = "Vertical" Then
		TypeOfDim = kVerticalDimensionType
	Else If DimensionType = "Horizontal" 
		TypeOfDim = kHorizontalDimensionType
	Else If DimensionType = "Aligned" 
		TypeOfDim = kAlignedDimensionType
	End If
	
	
	'Create the Dimension and Re-Center the text inbetween the leaders
	Dim oDimension As DrawingDimension
	oDimension = oSheet.DrawingDimensions.GeneralDimensions.AddLinear(oPt, oIntent1, oIntent2, TypeOfDim, True, DimStyle)
	
	'Return this Dimension
	Return oDimension

End Function

Function CreateDetailView (oDrawingDoc As DrawingDocument, oDrawingView As DrawingView, ScaleSize As Double, DimensionLength As DoubleForEquals, DirectionOfDim As String, DimensionLocation As String, PointLocation As String, Radius As Double)


	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oDrawingCurve As DrawingCurve
	Dim CorrectCurve As DrawingCurve
	Dim oTG As TransientGeometry
	Dim StartCount As Integer
	Dim oDetailView As DetailDrawingView
	Dim DrawingViewScale As Double
	
	DrawingViewScale = oDrawingView.Scale
	oTG = ThisApplication.TransientGeometry
	
		'//////////												//////////////////
	'//////////  SEE 'CreateLinearDimension' FOR THIS PORTION OF CODE  //////////////////
		'//////////												//////////////////
		
	If DimensionLocation = "Top" Or DimensionLocation = "Right" Then
		DrawingCurvePoint = oTG.CreatePoint2d(0, 0)
	Else If DimensionLocation = "Bottom" Or DimensionLocation = "Left" 
		DrawingCurvePoint = oTG.CreatePoint2d(100, 100)
	End If
	
	DrawingCurvePointX = DrawingCurvePoint.x
	
	Dim CurveCount As Integer
	CurveCount = 0
	
	For Each oDrawingCurve In oDrawingView.DrawingCurves
		CurveCount = CurveCount + 1
	Next
	
	
	For StartCount = 1 To CurveCount
		
		oDrawingCurve = oDrawingView.DrawingCurves.Item(StartCount)
		
		If oDrawingCurve.CurveType = kLineSegmentCurve Then
		
			Dim DimLength As DoubleForEquals
			
			If DirectionOfDim = "Vertical" Then
				DimLength = Abs(oDrawingCurve.StartPoint.y - oDrawingCurve.EndPoint.y)/DrawingViewScale/2.54
			Else If DirectionOfDim = "Horizontal" Then
				DimLength = Abs(oDrawingCurve.StartPoint.x - oDrawingCurve.EndPoint.x)/DrawingViewScale/2.54
			End If
	
			If Abs(DimLength - DimensionLength) < 0.0001 Then 
				If DirectionOfDim = "Vertical" And DimensionLocation = "Right" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX < oDrawingCurve.EndPoint.x
						DrawingCurvePointX = oDrawingCurve.EndPoint.x
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Vertical" And DimensionLocation = "Left" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.x
						DrawingCurvePointX = oDrawingCurve.StartPoint.x
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX > oDrawingCurve.EndPoint.x
						DrawingCurvePointX = oDrawingCurve.EndPoint.x
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Top" Then
					If DrawingCurvePointX < oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX < oDrawingCurve.EndPoint.y
						DrawingCurvePointX = oDrawingCurve.EndPoint.y
						CorrectCurve = oDrawingCurve
					End If
					
				Else If DirectionOfDim = "Horizontal" And DimensionLocation = "Bottom" Then
					If DrawingCurvePointX > oDrawingCurve.StartPoint.y
						DrawingCurvePointX = oDrawingCurve.StartPoint.y
						CorrectCurve = oDrawingCurve
					End If
					If DrawingCurvePointX > oDrawingCurve.EndPoint.y
						DrawingCurvePointX = oDrawingCurve.EndPoint.y
						CorrectCurve = oDrawingCurve
					End If
				End If
			End If
		End If
	Next
	
	
	
	
	Dim StartPoint As Point2d
	Dim EndPoint As Point2d
	Dim CenterPoint As Point2d
	Dim Coords As Point2d
	
	'Set the Start Point and End Point to the correct curve
	StartPoint = CorrectCurve.StartPoint
	EndPoint = CorrectCurve.EndPoint
	
	'Find the Center Point of the Detail based on the Parameters passed into the Sub
	If DirectionOfDim = "Horizontal" And PointLocation = "Left" Then
		If StartPoint.x < EndPoint.x Then
			CenterPoint = StartPoint
		Else
			CenterPoint = EndPoint
		End If
		
	Else If DirectionOfDim = "Horizontal" And PointLocation = "Right"
		If StartPoint.x > EndPoint.x Then
			CenterPoint = StartPoint
		Else
			CenterPoint = EndPoint
		End If
	
	Else If DirectionOfDim = "Vertical" And PointLocation = "Top"
		If StartPoint.y > EndPoint.y Then
			CenterPoint = StartPoint
		Else
			CenterPoint = EndPoint
		End If
		
	Else If DirectionOfDim = "Vertical" And PointLocation = "Bottom"
		If StartPoint.y < EndPoint.y Then
			CenterPoint = StartPoint
		Else
			CenterPoint = EndPoint
		End If
	End If
	
	
	'Create a phantom point to place the view (Changed after Rule in the Drawing template is run)
	Dim ViewPoint As Point2d
	ViewPoint = oTG.CreatePoint2d(5, 5)
	
	'Creates an anchor point to attach the Detail to 
	'(This Is Not the Detail View itself but the little circle that creates the view)
	Dim oAttachPoint As GeometryIntent
	oAttachPoint = oSheet.CreateGeometryIntent(CorrectCurve, kStartPointIntent)
	
	'Create the Detail View
	oDetailView = oSheet.DrawingViews.AddDetailView(oDrawingView, ViewPoint, kFromBaseDrawingViewStyle, True, CenterPoint, Radius, oAttachPoint, ScaleSize, False)
	
	'Return the View
	Return oDetailView

End Function

Sub AlignText (TargetText As DrawingDimension, DestinationText11 As DrawingDimension, DestinationText22 As DrawingDimension, Direction As String, Side As String)
	
	Dim oTG As TransientGeometry
	oTG = ThisApplication.TransientGeometry
	
	
	Dim Num11 As Double
	Dim Num22 As Double
	Dim StartPoint11 As Point2d
	Dim EndPoint11 As Point2d
	Dim Point11 As Point2d
	Dim StartPoint22 As Point2d
	Dim EndPoint22 As Point2d
	Dim Point22 As Point2d
	Dim CountStart As Integer
	Dim CountEnd As Integer
	CountEnd = 2
	
	
	'Set the Points
	Point11 = oTG.CreatePoint2d(0, 0)
	Point22 = oTG.CreatePoint2d(0, 0)
	
	'Set the Start Points and end points for both possible sides of the text alignment
	StartPoint11 = DestinationText11.IntentOne.PointOnSheet
	EndPoint11 = DestinationText11.IntentTwo.PointOnSheet
	
	StartPoint22 = DestinationText22.IntentOne.PointOnSheet
	EndPoint22 = DestinationText22.IntentTwo.PointOnSheet

	
	For CountStart = 1 To CountEnd
		
		Dim StartPoint As Point2d
		Dim EndPoint As Point2d
		Dim CorrectPoint As Point2d
		
		StartPoint = oTG.CreatePoint2d(0, 0)
		EndPoint = oTG.CreatePoint2d(0, 0)
		CorrectPoint = oTG.CreatePoint2d(0, 0)
		
		'Because the same calculations are needed for 3 different sets of variable, the variables will be replaced
		'with each cycle of the For loop
		If CountStart = 1 Then
			StartPoint = StartPoint11
			EndPoint = EndPoint11
			CorrectPoint = Point11
		Else If CountStart = 2
			StartPoint = StartPoint22
			EndPoint = EndPoint22
			CorrectPoint = Point22
		End If
		
		
		If Side = "Left" Then
			If StartPoint.x < EndPoint.x Then
				CorrectPoint = StartPoint
			Else 
				CorrectPoint = EndPoint
			End If
			
		Else If Side = "Right" Then
			If StartPoint.x > EndPoint.x Then
				CorrectPoint = StartPoint
			Else 
				CorrectPoint = EndPoint
			End If
			
		Else If Side = "Bottom" Then
			If StartPoint.y < EndPoint.y Then
				CorrectPoint = StartPoint
			Else 
				CorrectPoint = EndPoint
			End If
			
		Else If Side = "Top" Then
			If StartPoint.y > EndPoint.y Then
				CorrectPoint = StartPoint
			Else 
				CorrectPoint = EndPoint
			End If
		End If
		
		'Set the Variable to the Correct one
		If CountStart = 1 Then
			Point11 = CorrectPoint	
		Else If CountStart = 2
			Point22 = CorrectPoint		
		End If	
	Next

					
	'Set the Text to Align the Target Text with
	'You'll want to align with the smaller Line
	If Side = "Left"
		If Point11.x > Point22.x Then
			DestinationText = DestinationText11
		Else
			DestinationText = DestinationText22
		End If
	Else If Side = "Right"
		If Point11.x < Point22.x Then
			DestinationText = DestinationText11
		Else
			DestinationText = DestinationText22
		End If
	Else If Side = "Top"
		If Point11.y < Point22.y Then
			DestinationText = DestinationText11
		Else
			DestinationText = DestinationText22
		End If
	Else If Side = "Bottom"
		If Point11.y > Point22.y Then
			DestinationText = DestinationText11
		Else
			DestinationText = DestinationText22
		End If
	End If
	
	
	
	Dim dPosition As Double
	Dim oPosition As Point2d
	
	'Get the Origin Point of the Target Text
	oPosition = TargetText.Text.Origin
	
	'Align the Target Text according to the proper direction
	If Direction = "Vertical" Then
		dPosition = DestinationText.Text.Origin.Y
		oPosition.Y = dPosition
		
	Else If Direction = "Horizontal" Then
		dPosition = DestinationText.Text.Origin.X
		oPosition.X = dPosition
	End If
	
	'Set the Target text Origin
	TargetText.Text.Origin = oPosition 

End Sub

Sub CreateText (oDrawingDoc As DrawingDocument, ViewNumber As Double, oText As String, OffsetDistance As Double)

	Dim oSheet As Sheet
	Dim oDrawingView As DrawingView
	Dim oTG As TransientGeometry
	Dim oPoint As Point2d
	Dim TextPoint As Point2d
	Dim ViewWidth As Double
	Dim TextWidth As Double
	
	'Set the Drawing View based on the Index passed into the sub
	oSheet = oDrawingDoc.Sheets.Item(1)
	oDrawingView = oSheet.DrawingViews.Item(ViewNumber)
	oTG = ThisApplication.TransientGeometry
	
	TextPoint = oTG.CreatePoint2d(0, 0)
	
	
	Dim oGeneralNotes As GeneralNotes
	oGeneralNotes = oSheet.DrawingNotes.GeneralNotes
	
	'Randomly place the Text (oText is the string passed through the sub)
	Dim oGeneralNote As GeneralNote
	oGeneralNote = oGeneralNotes.AddFitted(oTG.CreatePoint2d(5, 5), oText)
	
	'Get the origin points of the View
	oPointx = oDrawingView.Position.x
	oPointy = oDrawingView.Position.y
	
	'Get the Lengths of the View and Text
	ViewWidth = oDrawingView.Width
	ViewHeight = oDrawingView.Height
	TextWidth = oGeneralNote.Width
	
	'This will Center the text width wise and place it at the OffsetDistance Vertically
	TextPoint.x = oPointx - TextWidth/2
	TextPoint.y = oPointy - ViewHeight + OffsetDistance
	
	'Set the TextPoint 
	oGeneralNote.Position = TextPoint

End Sub

Function FindViewIndex (oDrawingDoc As DrawingDocument, oDrawingView As DrawingView)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oView As DrawingView
	Dim ViewNumber As Integer
	
	Dim iIndex As Integer
	iIndex = 1
	
	'For Each View, Cycle through until the Current View is the Target View
	For Each oView In oSheet.DrawingViews
		If oView Is oDrawingView Then
			ViewNumber = iIndex
		End If
		iIndex = iIndex + 1
	Next
	
	'Return the Index Number
	Return ViewNumber

End Function


Sub CreateOverallDimension(oDrawingDoc As DrawingDocument, DimensionType As String, DimAlign As String, CurveMin As DrawingCurve, PointMin As String, CurveMax As DrawingCurve, PointMax As String, OffsetDistance As Double)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oTG As TransientGeometry
	oTG = ThisApplication.TransientGeometry


	Dim StartMin As Point2d
	Dim EndMin As Point2d
	Dim StartMax As Point2d
	Dim EndMax As Point2d
	Dim IntentMin As Point2d
	Dim IntentMax As Point2d
	Dim CountStart As Integer
	Dim CountEnd As Integer
	Dim PointAlign As Point2d
	CountEnd = 3
	
	IntentMin = oTG.CreatePoint2d(0, 0)
	IntentMax = oTG.CreatePoint2d(0, 0)
	PointAlign = oTG.CreatePoint2d(0, 0)
	
	'Get the Points of the First Curve
	StartMin = CurveMin.StartPoint
	EndMin = CurveMin.Endpoint
	
	'Get the Points of the Second Curve
	StartMax = CurveMax.StartPoint
	EndMax = CurveMax.Endpoint


	For CountStart = 1 To CountEnd
		
		Dim PointLocation As String
		Dim StartPoint As Point2d
		Dim EndPoint As Point2d
		Dim IntentPoint As Point2d
		Dim SelectCurve As DrawingCurve
		
		'For Each Curve, Run through the same calculations for each set of variables
		'Because the same calculations are needed for 3 different sets of variable, the variables will be replaced
		'with each cycle of the For loop
		If CountStart = 1 Then
			PointLocation = PointMin
			StartPoint = StartMin
			EndPoint = EndMin
			IntentPoint = IntentMin
			SelectCurve = CurveMin
			
		Else If CountStart = 2
			PointLocation = PointMax
			StartPoint = StartMax
			EndPoint = EndMax
			IntentPoint = IntentMax
			SelectCurve = CurveMax
			
		Else If CountStart = 3
			PointLocation = DimAlign
			StartPoint = IntentMin
			EndPoint = IntentMax
			IntentPoint = PointAlign
		End If
		
			
		If PointLocation = "Top" Then
			If StartPoint.y > EndPoint.y Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Bottom"
			If StartPoint.y < EndPoint.y Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Right"
			If StartPoint.x > EndPoint.x Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Left"
			If StartPoint.x < EndPoint.x Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Center"
			IntentPoint = SelectCurve.CenterPoint
		End If
		
		'Set the Variable to the Correct one
		If CountStart = 1 Then
			IntentMin = IntentPoint	
		Else If CountStart = 2
			IntentMax = IntentPoint		
		Else If CountStart = 3
			PointAlign = IntentPoint
		End If		
	Next


	Dim oDim As LinearGeneralDimension
	Dim oPt As Point2d
	Dim oPlaceDimX As Double
	Dim oPlaceDimY As Double
	Dim oIntent1 As GeometryIntent
	Dim oIntent2 As GeometryIntent

	'Set the Intent Points
	oIntent1 = oSheet.CreateGeometryIntent(CurveMin, IntentMin)
	oIntent2 = oSheet.CreateGeometryIntent(CurveMax, IntentMax)
	
	'Place the Dim Text 
	If DimensionType = "Vertical" Then
		oPlaceDimX = PointAlign.x + OffsetDistance
		oPlaceDimY = Abs(IntentMin.y - IntentMax.y)/2
	
	Else If DimensionType = "Horizontal"
		oPlaceDimX = Abs(IntentMin.x - IntentMax.x)/2
		oPlaceDimY = PointAlign.y + OffsetDistance
	End If
	

	Dim TypeOfDim As String
	
	If DimensionType = "Vertical" Then
		TypeOfDim = kVerticalDimensionType
	Else If DimensionType = "Horizontal" 
		TypeOfDim = kHorizontalDimensionType
	End If

	oPt = oTG.CreatePoint2d(oPlaceDimX, oPlaceDimY)
	
	'Create the Dim
	Dim oDimension As DrawingDimension
	oDimension = oSheet.DrawingDimensions.GeneralDimensions.AddLinear(oPt, oIntent1, oIntent2, TypeOfDim, True)
	oDimension.CenterText


End Sub

Sub CreateAngularDimension(oDrawingDoc As DrawingDocument, CurveMin As DrawingCurve, PointMin As String, OffsetDistanceX As Double, CurveMax As DrawingCurve, PointMax As String, OffsetDistanceY As Double)

	Dim oSheet As Sheet
	oSheet = oDrawingDoc.Sheets.Item(1)
	
	Dim oTG As TransientGeometry
	oTG = ThisApplication.TransientGeometry


	Dim StartMin As Point2d
	Dim EndMin As Point2d
	Dim StartMax As Point2d
	Dim EndMax As Point2d
	Dim IntentMin As Point2d
	Dim IntentMax As Point2d
	Dim CountStart As Integer
	Dim CountEnd As Integer
	CountEnd = 2
	
	IntentMin = oTG.CreatePoint2d(0, 0)
	IntentMax = oTG.CreatePoint2d(0, 0)
	
	StartMin = CurveMin.StartPoint
	EndMin = CurveMin.Endpoint
	
	StartMax = CurveMax.StartPoint
	EndMax = CurveMax.Endpoint

	
	'Find the Point intents based on Parameters passed into the Sub
	For CountStart = 1 To CountEnd
		
		Dim PointLocation As String
		Dim StartPoint As Point2d
		Dim EndPoint As Point2d
		Dim IntentPoint As Point2d
		Dim SelectCurve As DrawingCurve
		
		StartPoint = oTG.CreatePoint2d(0, 0)
		EndPoint = oTG.CreatePoint2d(0, 0)
		IntentPoint = oTG.CreatePoint2d(0, 0)
		
		'For Each Curve, Run through the same calculations for each set of variables
		'Because the same calculations are needed for 3 different sets of variable, the variables will be replaced
		'with each cycle of the For loop
		If CountStart = 1 Then
			PointLocation = PointMin
			StartPoint = StartMin
			EndPoint = EndMin
			IntentPoint = IntentMin
			SelectCurve = CurveMin
			
		Else If CountStart = 2
			PointLocation = PointMax
			StartPoint = StartMax
			EndPoint = EndMax
			IntentPoint = IntentMax
			SelectCurve = CurveMax
		End If
		
			
		If PointLocation = "Top" Then
			If StartPoint.y > EndPoint.y Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Bottom"
			If StartPoint.y < EndPoint.y Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Right"
			If StartPoint.x > EndPoint.x Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Left"
			If StartPoint.x < EndPoint.x Then
				IntentPoint = StartPoint
			Else 
				IntentPoint = EndPoint
			End If
			
		Else If PointLocation = "Center"
			IntentPoint = SelectCurve.CenterPoint
		End If
		
		
		If CountStart = 1 Then
			IntentMin = IntentPoint	
		Else If CountStart = 2
			IntentMax = IntentPoint		
		End If		
	Next


	Dim oDim As LinearGeneralDimension
	Dim oPt As Point2d
	Dim oPlaceDimX As Double
	Dim oPlaceDimY As Double
	Dim oIntent1 As GeometryIntent
	Dim oIntent2 As GeometryIntent

	'Create the Point Intent on the line
	oIntent1 = oSheet.CreateGeometryIntent(CurveMin)
	oIntent2 = oSheet.CreateGeometryIntent(CurveMax)
	
	'Set the Point Values
	oPlaceDimX = IntentMin.x + OffsetDistanceX
	oPlaceDimY = IntentMax.y + OffsetDistanceY
	
	'Create the Point
	oPt = oTG.CreatePoint2d(oPlaceDimX, oPlaceDimY)
	
	'Create the Dim and Center the Text
	Dim oDimension As DrawingDimension
	oDimension = oSheet.DrawingDimensions.GeneralDimensions.AddAngular(oPt, oIntent1, oIntent2)
	oDimension.CenterText


End Sub
